// Code generated by go generate; DO NOT EDIT.
package parser

import "github.com/vgalaktionov/glox/scanner"

type Expr interface {
	Accept(Visitor) interface{}
}

type Visitor func(Expr) interface{}

type Binary struct {
	Left Expr
	Operator scanner.Token
	Right Expr
}

func (e Binary) Accept(visitor Visitor) interface{} {
	return visitor(e)
}

type Grouping struct {
	Expression Expr
}

func (e Grouping) Accept(visitor Visitor) interface{} {
	return visitor(e)
}

type Literal struct {
	Value interface{}
}

func (e Literal) Accept(visitor Visitor) interface{} {
	return visitor(e)
}

type Unary struct {
	Operator scanner.Token
	Right Expr
}

func (e Unary) Accept(visitor Visitor) interface{} {
	return visitor(e)
}